name: continuous integration

on:
  pull_request: 
  push:
  workflow_dispatch: 

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v5

    - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        node-version: v24
        
    - uses: actions/setup-dotnet@baa11fbfe1d6520db94683bd5c7a3818018e4309 #v5.1.0
      with:
        dotnet-version: '8.0.x'

    - run: |
        chmod +x .github/workflows/script.sh
        .github/workflows/script.sh
    
    - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f #v6.0.0
      with:
       name: dist
       path: .

  called:
    uses: jessehouwing/action-demo/.github/workflows/callable.yaml@v2
    with:
      param1: test
